language: en-US
reviews:
  profile: chill
  high_level_summary: true
  commit_status: true
  auto_review:
    enabled: true
    drafts: false
tools:
  ruff:
    enabled: true
  pylint:
    enabled: true 
